### ISSUE TITLE
Add Rails 7.1 edge support

### ISSUE THREAD

**Issue by tagliala** [ifad/chronomodel#179]
```
  undefined method `direct_descendants' for class `#<Class:Bar(id: integer, name: string, foo_id: integer)>'
```

Bisected to rails/rails@1aa24639f788b06d54505f5aeb81a10f00f55e3d rails/rails#46144

```
ActiveSupport::DescendantsTracker.direct_descendants is deprecated and will be removed in Rails 7.1.
Use ActiveSupport::DescendantsTracker.subclasses instead.
```

**Comment by tagliala** [comment]
Another breaking change:

rails/rails@57bc28f728b1c6c78c550b1c72ed6a334dc52ccc rails/rails#44576

**Comment by tagliala** [comment]
Subclasses is not an alias of direct_descendants until 8f8aa857e084b76b1120edaa9bb9ce03ba1e6a19 rails/rails#39505

**Comment by tagliala** [comment]
subclasses doesn't work with Ruby 3.1 stable

**Comment by tagliala** [comment]
Another breaking change

```
  1) rails dbconsole rails dbconsole is expected to be successfully executed
     Failure/Error: specify { expect(last_command).to be_successfully_executed }

       Expected `bash -c "echo 'select 1 as foo_column; \q' | bundle exec rails db"` to succeed but got non-zero exit status and the following output:

       Unknown command-line client for chronomodel_railsapp.

  2) rails dbconsole rails dbconsole is expected to have output: /\bfoo_column\b/
     Failure/Error: specify { expect(last_command).to have_output(/\bfoo_column\b/) }
```

**Comment by tagliala** [comment]
dbconsole change:

rails/rails@4bcb8e4afbf4176a5d66054796eb7e9333ea9cd1 rails/rails#46093
