### ISSUE TITLE
Chronomodel breaks compatibility with the upcoming FactoryBot Rails 6.3.0

### ISSUE THREAD

**Issue by tagliala** [ifad/chronomodel#231]
Bisected to: thoughtbot/factory_bot_rails#419

```
NoMethodError: undefined method `config' for nil:NilClass
~/.rvm/gems/ruby-3.2.2/gems/railties-7.0.8/lib/rails.rb:47:in `configuration'
~/gems/ruby-3.2.2/bundler/gems/factory_bot_rails-659d74ae636c/lib/factory_bot_rails/railtie.rb:25:in `block in <class:Railtie>'
```

Live demo: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/tree/experimental/chrono-factory-bot-main

Proably chronomodel is hooking into Railties in a wrong way, since the default postgres adapter works

**Comment by tagliala** [comment]
https://github.com/ifad/chronomodel/blob/73626085cf9f42ad0fe6c821a4cc28dc0ba7c02a/lib/chrono_model.rb#L40-L48
